# Generated by Django 3.2.4 on 2021-06-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampstudentsuniteapi', '0002_alter_groupproject_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproject',
            name='github_link',
            field=models.CharField(max_length=150),
        ),
    ]
