# Generated by Django 3.2.4 on 2021-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampstudentsuniteapi', '0003_alter_groupproject_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproject',
            name='participants',
            field=models.ManyToManyField(related_name='participator', through='bootcampstudentsuniteapi.Participant', to='bootcampstudentsuniteapi.BootCampGraduate'),
        ),
    ]
